# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d4e4b034eb1a7d5ed3a38cafcc435dc8973d8dabb599ff537dfbba50feb1b708dab73b0dd8e684dd8ed869a916bcaba4b57be7dc920bf3d50a57b7da69eea4a

test:
  secret_key_base: f99d02b7bf031b85c561314e8f1d09b7f36d9987215f87c9452d06660aeb7e6ae58007917231024740cd7ed4c3ff0b3068a700d8df18d759e7bf0a9e3ec9c5a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
